// <auto-generated />
using System;
using DL.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DL.Migrations
{
    [DbContext(typeof(PBDataContext))]
    [Migration("20250217124053_V.1.0.0.0")]
    partial class V1000
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Models.NumberInfo", b =>
                {
                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("DateOfRegistration")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastUpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Number");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Numbers");

                    b.HasData(
                        new
                        {
                            Number = "+38012345678",
                            DateOfRegistration = new DateTimeOffset(new DateTime(2025, 2, 17, 14, 40, 53, 514, DateTimeKind.Unspecified).AddTicks(6593), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "",
                            FirstName = "",
                            FullName = "",
                            LastName = "",
                            LastUpdateDate = new DateTimeOffset(new DateTime(2025, 2, 17, 14, 40, 53, 514, DateTimeKind.Unspecified).AddTicks(6659), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Number = "+38023456781",
                            DateOfRegistration = new DateTimeOffset(new DateTime(2025, 2, 17, 14, 40, 53, 514, DateTimeKind.Unspecified).AddTicks(6663), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "",
                            FirstName = "",
                            FullName = "",
                            LastName = "",
                            LastUpdateDate = new DateTimeOffset(new DateTime(2025, 2, 17, 14, 40, 53, 514, DateTimeKind.Unspecified).AddTicks(6665), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Number = "+38034567812",
                            DateOfRegistration = new DateTimeOffset(new DateTime(2025, 2, 17, 14, 40, 53, 514, DateTimeKind.Unspecified).AddTicks(6667), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "",
                            FirstName = "",
                            FullName = "",
                            LastName = "",
                            LastUpdateDate = new DateTimeOffset(new DateTime(2025, 2, 17, 14, 40, 53, 514, DateTimeKind.Unspecified).AddTicks(6668), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Number = "+38045678123",
                            DateOfRegistration = new DateTimeOffset(new DateTime(2025, 2, 17, 14, 40, 53, 514, DateTimeKind.Unspecified).AddTicks(6670), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "",
                            FirstName = "",
                            FullName = "",
                            LastName = "",
                            LastUpdateDate = new DateTimeOffset(new DateTime(2025, 2, 17, 14, 40, 53, 514, DateTimeKind.Unspecified).AddTicks(6671), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Number = "+38056781234",
                            DateOfRegistration = new DateTimeOffset(new DateTime(2025, 2, 17, 14, 40, 53, 514, DateTimeKind.Unspecified).AddTicks(6672), new TimeSpan(0, 2, 0, 0, 0)),
                            Description = "",
                            FirstName = "",
                            FullName = "",
                            LastName = "",
                            LastUpdateDate = new DateTimeOffset(new DateTime(2025, 2, 17, 14, 40, 53, 514, DateTimeKind.Unspecified).AddTicks(6673), new TimeSpan(0, 2, 0, 0, 0))
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
