// <auto-generated />
using System;
using DL.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DL.Migrations
{
    [DbContext(typeof(PBDataContext))]
    partial class PBDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("Model.Models.NumberInfo", b =>
                {
                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateOfRegistration")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Number");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Numbers");

                    b.HasData(
                        new
                        {
                            Number = "+38012345678",
                            DateOfRegistration = new DateTimeOffset(new DateTime(2025, 2, 12, 14, 24, 42, 316, DateTimeKind.Unspecified).AddTicks(918), new TimeSpan(0, 2, 0, 0, 0)),
                            FirstName = "",
                            FullName = "",
                            LastName = "",
                            LastUpdateDate = new DateTimeOffset(new DateTime(2025, 2, 12, 14, 24, 42, 316, DateTimeKind.Unspecified).AddTicks(984), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Number = "+38023456781",
                            DateOfRegistration = new DateTimeOffset(new DateTime(2025, 2, 12, 14, 24, 42, 316, DateTimeKind.Unspecified).AddTicks(988), new TimeSpan(0, 2, 0, 0, 0)),
                            FirstName = "",
                            FullName = "",
                            LastName = "",
                            LastUpdateDate = new DateTimeOffset(new DateTime(2025, 2, 12, 14, 24, 42, 316, DateTimeKind.Unspecified).AddTicks(990), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Number = "+38034567812",
                            DateOfRegistration = new DateTimeOffset(new DateTime(2025, 2, 12, 14, 24, 42, 316, DateTimeKind.Unspecified).AddTicks(992), new TimeSpan(0, 2, 0, 0, 0)),
                            FirstName = "",
                            FullName = "",
                            LastName = "",
                            LastUpdateDate = new DateTimeOffset(new DateTime(2025, 2, 12, 14, 24, 42, 316, DateTimeKind.Unspecified).AddTicks(993), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Number = "+38045678123",
                            DateOfRegistration = new DateTimeOffset(new DateTime(2025, 2, 12, 14, 24, 42, 316, DateTimeKind.Unspecified).AddTicks(995), new TimeSpan(0, 2, 0, 0, 0)),
                            FirstName = "",
                            FullName = "",
                            LastName = "",
                            LastUpdateDate = new DateTimeOffset(new DateTime(2025, 2, 12, 14, 24, 42, 316, DateTimeKind.Unspecified).AddTicks(996), new TimeSpan(0, 2, 0, 0, 0))
                        },
                        new
                        {
                            Number = "+38056781234",
                            DateOfRegistration = new DateTimeOffset(new DateTime(2025, 2, 12, 14, 24, 42, 316, DateTimeKind.Unspecified).AddTicks(998), new TimeSpan(0, 2, 0, 0, 0)),
                            FirstName = "",
                            FullName = "",
                            LastName = "",
                            LastUpdateDate = new DateTimeOffset(new DateTime(2025, 2, 12, 14, 24, 42, 316, DateTimeKind.Unspecified).AddTicks(999), new TimeSpan(0, 2, 0, 0, 0))
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
